bankproject/bankapp/urls.py
from.import views
from django.urls import path
app_name='bankapp'

urlpatterns=[
    path('',views.home,name='home'),
    path('new/',views.new,name='new'),
    path('add/',views.customer_create_view,name='customer'),

    path('ajax/load-branches/', views.load_branches, name='ajax_load_branches'),

]

bankproject/bankproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',include('bankapp.urls')),
    path('credentials/',include('credentials_app.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

bankproject/credentials_app/urls.py
from . import views
from django . urls import path
app_name='credentials_app'

urlpatterns=[
    path('register/',views.register,name='register'),
    path('login/',views.login,name='login'),
    path('logout',views.logout,name='logout'),
]

bankproject/bankapp/models.py
from django .db import models
from multiselectfield import MultiSelectField



# Create your models here
class District(models.Model):
    Name = models.CharField(max_length=200)




    def __str__(self):
        return self.Name


class Branch(models.Model):
    Name = models.CharField(max_length=200)
    District = models.ForeignKey(District, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.Name

choices=[('Female','Female'),('Male','Male'),('Other','Other')]
accounts=[('Current Account','Current Account'),('Savings','Savings'),('RD Account','RD Account'),
          ('FD Account','FD Account'),('NRI Account','NRI Account')]
materials=(('Debit Card','Debit Card'),('Credit Card','Credit Card'),('Cheque Book','Cheque Book'))

class Customer(models.Model):
    Name = models.CharField(max_length=100)
    Date_of_birth=models.DateField(null=True,blank=True)
    Age = models.IntegerField()
    Gender = models.CharField(max_length=20,choices=choices)
    Phone_number = models.IntegerField()
    Mailid = models.EmailField()
    Address = models.TextField()
    District = models.ForeignKey(District, on_delete=models.SET_NULL, null=True)
    Branch = models.ForeignKey(Branch, on_delete=models.SET_NULL, null=True)
    Account_type = models.CharField(max_length=100,choices=accounts)
    Materials = MultiSelectField(choices=materials,max_choices=3,max_length=100)

    def __str__(self):
        return self.Name

bankproject/bankapp/forms.py
from django import forms
from . models import Branch,District,Customer


class CustForm(forms.ModelForm):
    class Meta:
        model=Customer
        fields= "__all__"
        widgets={ 'Date_of_birth':forms.DateInput(
            attrs={'type':'date','placeholder':'yyyy-mm-dd(DOB)','class':'form-control'}
        )}
        # Date_of_birth=forms.DateField(



    def __init__(self,  *args, **kwargs):
        super().__init__(*args,**kwargs)
        # if request_change:
        #     request_change=False
        # else:
        self.fields['Branch'].queryset=Branch.objects.none()

        if 'District' in self.data:
            try:
                district_id=int(self.data.get('District'))
                self.fields['Branch'].queryset=Branch.objects.filter(District_id=district_id).order_by('Name')
            except (ValueError,TypeError):
                pass
        # elif self.instance.pk:
        #     self.fields['Branch'].queryset=self.instance.District.Branch_set.order_by('Name')

bankproject/bankapp/views.py
from django.shortcuts import render,redirect

import bankapp
from .forms import CustForm
from .models import Customer,Branch
from django.contrib import messages
app_name=bankapp

# Create your views here.
def home(request):
    return render(request,'index.html')
def new(request):
    return render(request,'new.html')
# def custreg(request):
#     return render(request,'customer.html')
def customer_create_view(request):
    form=CustForm()
    if request.method=='POST':
        # CustForm.request_change=True
        form=CustForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Application submit successfully")
            # form=CustForm()
            # return redirect('add/')

    return render(request,'customer.html',{'form':form})


# Ajax
def load_branches(request):
    district_id=request.GET.get('District_id')
    branchs=Branch.objects.filter(District_id=district_id).all()
    return render(request,'branch_list_options.html',{'branchs':branchs})

bankproject/credentials_app/views.py
from django.shortcuts import render
from django.contrib import messages,auth
from django.contrib.auth.models import User
from django.shortcuts import render,redirect
import credentials_app
app_name=credentials_app
# Create your views here.

#login
def login(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        user=auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request, user)
            # return render(request,'new.html')
            return render(request,'new.html')
        else:
            messages.info(request, "Invalid credentials")
            return render(request,'login.html')

    else:
        return render(request,'login.html')



# Register

def register(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        cpwd=request.POST['password1']
        if password==cpwd:
            if User.objects.filter(username=username).exists():
                messages.info(request,"Username Taken")
                return render(request,'register.html')
            else:
                user = User.objects.create_user(username=username, password=password)
                user.save()
                return render(request,'login.html')
        else:
            messages.info(request,'Password not matching')
            return render(request,'register.html')
    else:
        return render(request,'register.html')
            


# logout
def logout(request):
    auth.logout(request)
    return render(request,'index.html')

bankproject/templates/branch_list_options.html
<option value="">---Select---</option>
{% for branch in branchs %}
<option value="{{branch.pk}}">{{branch.Name}}</option>
{% endfor %}

bankproject/templates/customer.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
<!--    <link rel="stylesheet" href="{% static 'css/custom.css' %}">-->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <title>Registration Page</title>
</head>
<body style="background-color:#9370db;">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Josefin+Sans&family=Libre+Baskerville&family=Roboto:ital,wght@1,700&family=Young+Serif&display=swap" rel="stylesheet">
<div class="Container">
<center><h2>Customer Registration Form</h2></center>
  </div>
<div class="container">
    <div class="col sm-6" >

           <form id="CustForm" method="POST" data-branches-url="{% url 'bankapp:ajax_load_branches' %}" >

             {% csrf_token %}
               <table>
             {{ form.as_table }}
               </table>

  <button type="submit" class="btn btn-success">Submit</button>
   <a href="{% url 'credentials_app:logout' %}" class="btn btn-secondary">Logout</a>
</form>

        {% for msg in messages %}
            <h4 style="color:red;">{{msg}}</h4>
        {% endfor %}
        <a href="{% url 'bankapp:home' %}" style="color:black;"><strong>Home Page</strong></a>
    </div>

</div>
</div>
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_District").change(function () {
    const url = $("#CustForm").attr("data-branches-url");
    const DistrictId = $(this).val();
     $.ajax({
            url: url,
            data: {
                'District_id': DistrictId
            },
            success: function (data) {
                console.log(data)
                $("#id_Branch").html(data);
            }
        });

    });

</script>







<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>

bankproject/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <title>Banking System</title>
</head>
<body>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Josefin+Sans&family=Libre+Baskerville&family=Roboto:ital,wght@1,700&family=Young+Serif&display=swap" rel="stylesheet">
<div class="container-image">
    <img src="/static/image/bankimage.jpg" alt="" style="width:100%">
</div>
<!--header-->
<header>

<!--navbar-->
<nav class="navbar navbar-expand-lg bg-body-primary">
  <div class="container-fluid">
      <img  class="my-image" src="{% static 'image/logo.jpg' %}" alt="logo_image" width="50px;" height="50px;">
    <a class="navbar-brand" href="#"><h2>Banking System</h2></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="row-mx-auto">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Branches
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Pathanamthitta">Pathanamthitta</a></li>
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Alappuzha">Alappuzha</a></li>
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Ernakulam">Ernakulam</a></li>
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Trivandrum">Trivandrum</a></li>
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kottayam">Kottayam</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'credentials_app:login' %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'credentials_app:register' %}">Register</a>
        </li>
      </ul>
    </div>
    </div>
  </div>
</nav>
</header>
<div class="container" >
      <div class="row">
        <div class="col-xl-6">
          <h2>Welcome to Banking System.We are team of talented employees.</h2>
          <a href="{% url 'credentials_app:login' %}" class="btn btn-primary">Get Login</a>
        </div>
      </div>
    </div>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

bankproject/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
<!--    <link rel="stylesheet" href="{% static 'css/custom.css' %}">-->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <title>Login Page</title>
</head>
<body style="background-color:#8fbc8b;">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Josefin+Sans&family=Libre+Baskerville&family=Roboto:ital,wght@1,700&family=Young+Serif&display=swap" rel="stylesheet">

<!--<div class="register-image">-->
<!--      <img src="/static/image/bagr1.jpg" alt="" style="width:100%;">-->
<!--</div>-->
<div class="container">
    <div class="card m-5 p-5" style="width:18 rem;" >
     <div class="card-body">
         <center><h4 class="card-title">User Login</h4></center>

            <form  action="{% url 'credentials_app:login' %}" method="post" >
                {% csrf_token %}
                <div class="form-group">
                    <input type="text" class="form-control" name="username" placeholder="Enter user_name">
                </div>
                <br>
                <div class="form-group">
                    <input type="password" class="form-control" name="password" placeholder="Enter password">
                </div>
                 <br>
                <button type="submit" class="btn btn-success"> Login</button>

<!--                <a href="{% url 'bankapp:new' %}" class="btn btn-success btn-block ">Login</a>-->
                Click for <a href="{% url 'credentials_app:register' %}">Register</a>
            </form>
         <div>
             {% for message in messages %}
             <h3>{{message}}</h3>
             {% endfor %}
         </div>
</div>
    </div>
</div>


<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>

bankproject/templates/new.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <title>New Page</title>
</head>
<body style="background-color:#b22222;">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Josefin+Sans&family=Libre+Baskerville&family=Roboto:ital,wght@1,700&family=Young+Serif&display=swap" rel="stylesheet">

<div class="container">
    <br>
     <div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 ">

<!--        <div class="col-sm-6">-->
        <div class="card" style="width:18rem;">
            <div class="card-body">
                <form method="POST">
          {% csrf_token %}
           <p class="card-text" style="color:#c71585; font-size:18px;text-align:center; font-weight:bold;">Click below button for customer registration </p> <br>
          <a href="{% url 'bankapp:customer' %}" class="btn btn-secondary">Customer Registration</a>


</form>
           </div>
        </div>
        </div>
    </div>
</div>
</body>
</html>

bankproject/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
<!--    <link rel="stylesheet" href="{% static 'css/custom.css' %}">-->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <title>Registration Page</title>
</head>
<body style="background-color:#9370db;">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Josefin+Sans&family=Libre+Baskerville&family=Roboto:ital,wght@1,700&family=Young+Serif&display=swap" rel="stylesheet">

<!--<div class="register-image">-->
<!--      <img src="/static/image/bagr1.jpg" alt="" style="width:100%;">-->
<!--</div>-->
<div class="container">
    <div class="card m-5 p-5" style="width:18 rem;" >
     <div class="card-body">
         <center><h4 class="card-title">User Registration</h4></center>
            <form action="{% url 'credentials_app:register' %}" method="POST" >
                {% csrf_token %}
                <div class="form-group">
                    <input type="text" class="form-control" name="username" placeholder="Enter user_name">
                </div>
                <br>
                <div class="form-group">
                    <input type="password" class="form-control" name="password" placeholder="Enter password">
                </div>
                <br>
                <div class="form-group">
                    <input type="password" class="form-control" name="password1" placeholder="Enter confirm password">
                </div>
                <br>
                 <button type="submit" class="btn btn-success"> Register</button>
<!--                <a href="{% url 'credentials_app:login' %}" class="btn btn-success btn-block ">Register</a>-->

            </form>
         <div>
             {% for message in messages %}
                 <h3>{{message}}</h3>
                {% endfor %}
         </div>
</div>
    </div>
</div>


<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>